### PR TITLE
cudacpp install (with versioning in the madgraph4gpu repo without an info.dat file)

### PR DESCRIPTION
**Pull request by valassi**
Hi @oliviermattelaer this is a WIP for cudacpp installer

It is almost all ok, but I am having trouble with github tags and releases on madgraph4gpu, which is what I wanted to do.

Far too tired to do this now, maybe tomorrow.

The idea is to have a tar.gz with name like 3.6.0_latest, and then to have this as a running tag on madgraph4gpu (but this is the tricky bit I do not manage)

Feel free to have a look alrteady, but it is wip. Will not work because I did not manage to recreate the tag on madgraph4gpu (I had managed with a zip before, but that does not keep patchMad.sh permissions so I went back to tar.gz)

### CODE REVIEW

**Comment by oliviermattelaer** [comment]
So here you do not want to use the external database of link (and his smart association of link)?
(You have remove the www path and the associated  MG5_specific keyword for such handling?)

This is really needed such that I can release any new release of MG5 without needing to create a new tarball for cudacpp (except if this is needed).

Now for your test (and or for good), you can obviously change the adress of that link.

For tag, they are suppose to be frozen in time, if you want something moving, then this is suppose to be a branch.
Now we can do the same with "formated tag" x.y.z_for_360 such that they are both unique and with the information needed for 3.6.0 (and the CI might be able to create the associate asset)

**Comment by valassi** [comment]
> So here you do not want to use the external database of link (and his smart association of link)? (You have remove the www path and the associated MG5_specific keyword for such handling?)
> 
> This is really needed such that I can release any new release of MG5 without needing to create a new tarball for cudacpp (except if this is needed).

Hi @oliviermattelaer thanks :-)

Listen the answer to "do I want to do that" is "I do not know, I want to discuss this with you but I am testng in the meantime". I find it easier to discuss once I get a better idea of what goes on and what can be done and what cannot be done technically.

> Now for your test (and or for good), you can obviously change the adress of that link.

Anyway, somehow magically this morning this worked. (I need to understand why/how). The issue that I had yesterday evening was that I had created this tag TEST_cudacpp_for3.6.0_latest in a wrong way, an dI wanted to delete it and recreate it, then I deleted it but I was unable to recreate it. I was going to investigate this morning, then I just tried to create it again (doing exactly what I did yesterday evening, via the web), and this time it worked! The tag and releasse were created, this launched a CI job that created a tar.gz archive and made it available:
https://github.com/valassi/madgraph4gpu/releases/tag/TEST_cudacpp_for3.6.0_latest

Then I just tried the rest of the infrastructure including this very change #6 for HEPToolsInstaller, an dthings worked out of the box!

So this is my current recipe (cc @roiser for info)
```
# Install mg5amcnlo
# [bash> prompt]
git clone git@github.com:mg5amcnlo/mg5amcnlo.git
cd mg5amcnlo
git remote add valassi git@github.com:valassi/mg5amcnlo.git
git fetch valassi
git checkout --track valassi/valassi_cudacpp_install
cd ..

# Install HEPToolsInstallers.git
# [bash> prompt]
git clone git@github.com:mg5amcnlo/HEPToolsInstallers.git
cd HEPToolsInstallers
git remote add valassi git@github.com:valassi/HEPToolsInstallers
git fetch valassi
git checkout --track valassi/valassi_cudacpp
cd ..

# Set up compilers, ccache etc
env | egrep '(^CC|^CXX|^FC|CCACHE)'
# [Results below]
# CCACHE_DIR=/data/avalassi/GPU2023/ccache
# CXX=g++
# USECCACHE=1
# FC=gfortran
# CC=gcc

# Install the cudacpp tarball (currently from a madgrah4gpu release)
# See https://github.com/valassi/madgraph4gpu/releases/tag/TEST_cudacpp_for3.6.0_latest
# [bash> prompt]
cd mg5amcnlo
./bin/mg5_aMC
# [MG5_aMC> prompt]
install cudacpp --local
generate e+ e- > mu+ mu-
output madevent_simd ee_mumu.mad --hel_recycling=False --vector_size=32
launch
# [Results below]
#  ...
#  wget --no-check-certificate https://github.com/valassi/madgraph4gpu/releases/download/TEST_cudacpp_for3.6.0_latest/cudacpp.tar.gz
#  ...
#  === Results Summary for run: run_01 tag: tag_1 ===
#
#     Cross-section :   0.1042 +- 5.767e-05 pb
#     Nb of events :  10000
```

> For tag, they are suppose to be frozen in time, if you want something moving, then this is suppose to be a branch.
> Now we can do the same with "formated tag" x.y.z_for_360 such that they are both unique and with the information needed for 3.6.0 (and the CI might be able to create the associate asset)

This is one thing to be discussed, precisely. There are many options possible, many choices and many questions.

One question is whether you want the archive to be created externally or you want it to be created internally in madgraph4gpu (soon to be renamed). The solution above is based on doing things internally
https://github.com/valassi/madgraph4gpu/blob/cefe0dbe167f4e8fe073b3a121acf4e9ea149fb5/.github/workflows/archiver.sh
https://github.com/valassi/madgraph4gpu/blob/cefe0dbe167f4e8fe073b3a121acf4e9ea149fb5/.github/workflows/archiver.yml

I agree that we need a branch at some point for a "release series" maintenance. But then the question remains, do you want the madgraph4gpu CI to build the tar.gz (then you need a tag and a release: non-release assets are kept a maximum of 90 days, while release assets are hopefully kept forever), or do you build it outside. Both are valid options.

And then the second question, somehat independent, is do you also want an external database to do the matching in HEPToolsInstaller, or is it enough to define a consistent tagging policy and just do it as I did above. Both are valid options.

One of the main reasons why I tested like this is that I am able to control the full chain for a test. If I wanted to test an external database in Louvain or Milano I would need wrte privileges, or wait for you to do that. In production that's clearly possible (and maybe better so you centralise). For development I wanted to test the full thing, and it seems to work.

Now I will go back to try to understand a few points in the tag/release/CI of madgraph4gpu, I think this is useful anyway unless you tell me we will absolutely build the tar.gz outside the repo and not in its CI).

Thanks
Andrea

**Comment by valassi** [comment]
Hi @oliviermattelaer as discussed in https://github.com/madgraph5/madgraph4gpu/pull/1008#issuecomment-2379776895 I mark this as ready for review.

Which means ready for discussion actually, as you might want to do things differently. But again, **the whole chain works**.

I would give it a try to use this approach where there is no need for an info.dat database file. Then if we find it not appropriate it can be changed. But again, for the moment there is no need for it. Let's discuss next week.

Thanks, bon weekend
Andrea

**Comment by valassi** [comment]
> So here you do not want to use the external database of link (and his smart association of link)? (You have remove the www path and the associated MG5_specific keyword for such handling?)
> 
> This is really needed such that I can release any new release of MG5 without needing to create a new tarball for cudacpp (except if this is needed)

PS on this point, lets take an example: you have released 3.6.0 (with a 1.0.0 cudacpp i.e. a tag cudacpp_for3.6.0_v1.0.0), and now you want to release 3.6.1.

Strictly speaking, I guess that in any case we would probably validate cudacpp against 3.6.1, so there would be a submodule update to something pointing 3.6.1. In that case, you just need to create a tag like
```
./gitTag.sh  1.0.1
```
and the script would realise that there is a link to 3.6.1 and would create a tag called cudacpp_for3.6.1_v1.0.1, so not much to do.

If instead there was no time/need to change the cudacpp code and you want to use AS-IS that same cudacpp_for3.6.0_v1.0.0 tarball for 3.6.1, then you just need to create two releases cudacpp_for3.6.1_v1.0.0 and cudacpp_for3.6.1_latest on the web interface, poiting to master. (Or it's even enough that you run 'git tag cudacpp_for3.6.1_v1.0.0` and `git tag cudacpp_for3.6.1_latest` from the command line!). If you create a release (or even just a tag), the archiver.yml CI runs in any case, and creates the tarball, and uploads it a posteriori to that release.

So to me this looks quite easy from a release management point of view. But lets discuss next week.

**Comment by oliviermattelaer** [comment]
Hi,

> One question is whether you want the archive to be created externally or you want it to be created internally in madgraph4gpu (soon to be renamed). 

For me, both options are fine/equivalent.

> And then the second question, somehat independent, is do you also want an external database to do the matching in HEPToolsInstaller, or is it enough to define a consistent tagging policy and just do it as I did above. Both are valid options.

I would say that the tagging policy is not enough. And such database is mandatory.
I can create such file automatically on the madgraph server if you can not (or do not want to handle those internally).

> So to me this looks quite easy from a release management point of view. But lets discuss next week.

I agree, but we need such layer.

**Comment by valassi** [comment]
Hi @oliviermattelaer (cc @roiser) all good for me now. I have made the cudacpp 1.00.00 tags and releases

https://github.com/madgraph5/madgraph4gpu/releases/tag/cudacpp_for3.6.0_v1.00.00

https://github.com/madgraph5/madgraph4gpu/releases/tag/cudacpp_for3.6.0_latest

And the version info file is there

https://github.com/madgraph5/madgraph4gpu//releases/download/cudacpp_for3.6.0_latest/cudacpp.tar.gz

I would proceed as follows
- Merge https://github.com/madgraph5/madgraph4gpu/pull/1008 for cudacpp (then bump version to 1.00.01 immediately)
- Merge this https://github.com/mg5amcnlo/HEPToolsInstallers/pull/6
- Announce on the dev list

I will also send you a private email to discuss this

Thanks again!
Andrea

**Pull request merged**
