### PR TITLE
add hepmc3 and fix rivet compilation

### PR DESCRIPTION
**Pull request by sihyunjeon**

### CODE REVIEW

**Comment by sihyunjeon** [comment]
rivet works

**Comment by sihyunjeon** [comment]
i just realized i tested with 3.1.9, will check with 3.1.10 and update this PR accordingly

**Comment by sihyunjeon** [comment]
https://github.com/mg5amcnlo/HEPToolsInstallers/issues/3

**Comment by sihyunjeon** [comment]
found it working after

```
export LD_LIBRARY_PATH=/home/shjeon/Work/Physics/Generators/MG5_aMC_v3_5_3/HEPTools/hepmc/lib:$LD_LIBRARY_PATH
export LD_LIBRARY_PATH=/home/shjeon/Work/Physics/Generators/MG5_aMC_v3_5_3/HEPTools/fastjet/lib:$LD_LIBRARY_PATH
```

was added to run_rivet.sh, will make a PR for this to madgraph

**Comment by sihyunjeon** [comment]
goes along with the patch (though not necessarily) in https://github.com/mg5amcnlo/mg5amcnlo/pull/88

changed both rivet and yoda to the latest release in 3.1.x and 1.9.x era (which is at this point outdated, having 4.0.x and 2.0.x). but switching to  rivet4.0.x requires hepmc3 updates. so this PR just serves one of the milestones to move up to 4.0.x later on

**Comment by sihyunjeon** [comment]
there's something need to be checked

**Comment by oliviermattelaer** [comment]
For me this is ready to be merged.
But you have some doubt?

**Comment by sihyunjeon** [comment]
install path for fastjet no longer works, it redirects to "fastjet-config" instead of the directory itself

**Comment by sihyunjeon** [comment]
after the fix you suggested 

            if value and not os.path.isdir(value):
                value = os.path.dirname(value)
            if value and os.path.basename(value) == "bin":
                value = os.path.dirname(value)

i can see that fastjet is now properly being taken in heptoolsinstaller

**Pull request merged**
